### ISSUE TITLE
Creation of new file /dirs fails in root due to permission issues.

### ISSUE THREAD

**Issue by Joker9944** [mgutt/docker-apachewebdav#2]
### Expected Behavior
**Request:**
`curl -k --user admin:admin123 -X MKCOL https://localhost/test`
**Response:**
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>201 Created</title>
</head><body>
<h1>Created</h1>
<p>Collection /test has been created.</p>
</body></html>
```
### Current Behavior
**Request:**
`curl -k --user admin:admin123 -X MKCOL https://localhost/test`
**Log:**
```
BDB0004 fop_read_meta: /var/lib/dav/DavLock: unexpected file type or format
BDB0004 fop_read_meta: /var/lib/dav/DavLock: unexpected file type or format
BDB0004 fop_read_meta: /var/lib/dav/DavLock: unexpected file type or format
[Mon Oct 04 14:58:21.237057 2021] [dav:error] [pid 223:tid 140484478421792] (13)Permission denied: [client 172.19.0.1:47470] Unable to create collection.  [403, #0]
172.19.0.1 - admin [04/Oct/2021:14:58:21 +0000] "MKCOL /test HTTP/2.0" 403 199 "-" "curl/7.68.0"
```
### How to reproduce
```
---
version: '3.9'

services: 
  dav:
    image: 'apachewebdav/apachewebdav'
    ports:
      - '443:443'
    environment:
      - SERVER_NAMES=localhost
      - REALM=dav
      - USERNAME=admin
      - PASSWORD=admin123
      - SSL_CERT=selfsigned
```
### Explanation
The directory `/var/lib/dav/data` belongs to root with 0755 permission which does not allow to create the user running httpd new files under the data root.
### Fix
Change the owner of `/var/lib/dav/data` to the one running httpd.
